language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t motomaniak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true motomaniak/react-test npm test

after_success:
  - docker build -t motomaniak/multi-client ./client
  - docker build -t motomaniak/multi-nginx ./nginx
  - docker build -t motomaniak/multi-server ./server
  - docker build -t motomaniak/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push motomaniak/multi-client
  - docker push motomaniak/multi-nginx
  - docker push motomaniak/multi-server
  - docker push motomaniak/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'mult-docker'
  env: 'MultDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-372424862330'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

